In [2]:
import numpy as np

Numpy ofrece muchas opciones para la construcción y manejo de de arrays.

Consideremos una lista

In [14]:
L1 = [1,2,3,4,5,6,7,8,9]

con numpy podemos transformala en un array

In [15]:
x1 = np.array(L1)

In [16]:
x1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# podemos especificar el tipo de datos que queremos

In [18]:
x2 = np.array(L1, dtype = "float32")

In [19]:
x2

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

otras formas de crear arreglos:

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3,12,dtype = np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [25]:
np.arange(4,5,0.1) #(start,stop,step)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [27]:
np.linspace(1,7,12) # 12 números del 1 al 7 igualmente espaciados

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

cuando necesitemos la matriz identidad:

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Tambien podemos hacer modificaciones

In [33]:
x = np.zeros((8,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

supongamos que queremos distribuir estos 24 números en otra distribución de filas columnas, esto es

In [34]:
x.reshape((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Evidentemente la distribución debe ser valida.

otra función muy util es ravel, esta devuelve el mismo array pero de forma unidimensional

In [46]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
# una variante interesante es flatten, que devuelve una copia del array en una dimensión

In [44]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

Para transponer filas y columnas

In [48]:
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Ejercicios

1. Crear un array de datos con valores entre 5 y 120
2. Crear una matriz de 4x4 con valores desde 0 hasta 15
3. Crear la identidad 7x7
4. Crear un array de 20 elementos y transformarlos en una matriz de 5x4
5. Crear un array con 20 números con valores entre 0 y 5 espaciados de forma uniforme

In [51]:
#Ejercicio 1
x1 = np.arange(5,120)
x1

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [63]:
#Ejercicio 2

x2 = np.arange(16)
x2.reshape((4,4))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
#Ejercicio 3

np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [69]:
#Ejercicio 4

x4 = np.arange(1,21,1)
x4.reshape((5,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [70]:
# Ejercicio 5 

x5 = np.linspace(0,5,20)
x5

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [71]:
x5.size

20

## Propiedades de los arrays

comencemos con un array de datos

In [166]:
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [167]:
# n° de dimensión
x.ndim 

2

In [168]:
x.shape

(3, 4)

In [169]:
# n° total de elementos que tiene la matriz
x.size

12

In [170]:
#tipo de dato que contiene la matriz
x.dtype

dtype('int64')

In [171]:
#tamaño en bytes de cada uno de los elementos de la matriz
x.itemsize

8

In [172]:
#para acceder a la fila n°2

x[2]

array([ 8,  9, 10, 11])

In [173]:
#para acceder a nun elemento en particular
x[2,1]

9

In [174]:
# otra forma de redimensionar la matriz como con reshape es

x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Si queremos obtener una sub-matriz podemos emplear la siguiente sintaxis

In [175]:
x[1:3,0:2] #fila de 1 a 2 y columna de  0 a 1

array([[3, 4],
       [6, 7]])

In [176]:
# tambien podemos hacer esto con arrays unidimensionales

y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [177]:
y[3:8]

array([3, 4, 5, 6, 7])

In [178]:
y[1:7:2] # de dos en dos

array([1, 3, 5])

Podemos hacer el step con saltos de mayor a menor

In [179]:
z = np.arange(10,6,-1)
z

array([10,  9,  8,  7])

In [180]:
# tambien podemos indexar con arrays

y[z]

array([10,  9,  8,  7])

numpy es bastante flexible, ya que tambien nos permite acceder a los elementos por condición booleana

In [181]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [182]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [183]:
cond = x<25
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

podemos asignar un valor a todo un conjunto

In [184]:
x[12:24] = 1

In [185]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [186]:
x[13:16] = [9,6,12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  9,  6, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

nota: Si queremos realizar la siguiente asignación

In [194]:
x[5] = 3.1415
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  9,  6, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

Notemos que el resultado no es como lo esperabamos, esta es una de las debilidades de los arrays, *los datos deben ser homogeneos*, debido a esto, es que nuestra asignación fue redondeada, nuestro array contiene objetos enteros

In [3]:
#pequeño ejercicio:
#Modificando elementos de la matriz identidad
v = np.eye(7)

In [4]:
v

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [5]:
v[:,0] = 5

array([5., 5., 5., 5., 5., 5., 5.])

In [198]:
v[0,:] = 2

In [199]:
v[:,6] = 3 

In [200]:
v[6,:] = 4

In [201]:
v[2:5,:] = [x for x in range(1,8)]
v

array([[2., 2., 2., 2., 2., 2., 3.],
       [5., 1., 0., 0., 0., 0., 3.],
       [1., 2., 3., 4., 5., 6., 7.],
       [1., 2., 3., 4., 5., 6., 7.],
       [1., 2., 3., 4., 5., 6., 7.],
       [5., 0., 0., 0., 0., 1., 3.],
       [4., 4., 4., 4., 4., 4., 4.]])

## Copias y vistas de array

In [202]:
x = np.arange(10)

In [205]:
y = x
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [206]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

aquí hay que tener cuidado, para hacer una copia de un array podemos recurrir al metodo copy

In [208]:
z = x.copy()

In [209]:
z is x

False

In [210]:
x is y

True

Tambien podemos tener la vista de un objeto

In [211]:
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [215]:
t.shape = (5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [216]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [217]:
x is t

False

In [218]:
t[:] = 5

In [219]:
t

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [220]:
x

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

¿Qué paso aquí?, primero hemos hecho un reshape en la vista t, y *X* no ha cambiado, luego hemos cambiado información de t y ahora *X* si ha cambiado.
Esto es debido a que las vistas no comparten propiedades pero si información, por lo que hay que tener cuidado cuando obtengamos submatrices a partir de "rebanados", debido a que estas son precisamente, vistas del array original,

## Funciones Universales (ufunc)

In [221]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [222]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [223]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [224]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [227]:
alpha = np.linspace(0,2*np.pi,4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [228]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [229]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [231]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [232]:
# para 2**x
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [233]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [235]:
# Tambien puede ser al reves
np.power(x,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [236]:
np.sum(x)

45

In [240]:
np.nansum(x) # suma eliminando posibles valores nan

45

la mayoria de las funciones que veremos de aquí en adelante tienen su versión nan

In [242]:
#producto de todos los elementos del arreglo
np.prod(x)

0

In [243]:
np.min(x)

0

In [244]:
np.max(x)

9

In [245]:
np.std(x)

2.8722813232690143

In [246]:
np.var(x)

8.25

In [253]:
np.argmax(x)

9

In [248]:
np.argmin(x)

0

In [249]:
np.percentile(x,q=0.95)

0.08549999999999999

para arrays con valores booleanos

In [250]:
y = np.array([True,True,False,True])

In [251]:
np.any(y) # Devuelve True si es que existe algun elemento con valor True

True

In [252]:
np.all(x) # Devuelve True si todos los elementos del array son True

False

apliquemos algunas de las operaciones ya mencionadas sobre filas y columnas del array

In [261]:
np.random.seed(1995) 
z = np.random.random((3,5))
z

array([[0.34852587, 0.37221096, 0.44454252, 0.57955012, 0.9640571 ],
       [0.96120518, 0.24698024, 0.69583739, 0.40619613, 0.73440091],
       [0.17586907, 0.41113053, 0.75467997, 0.83594502, 0.19013114]])

In [262]:
# Suma de todo el conjunto de  valores
z.sum()

8.121262136563452

In [263]:
# suma por filas
z.sum(axis = 1)

array([2.70888657, 3.04461984, 2.36775573])

In [264]:
# suma por columnas
z.sum(axis = 0)

array([1.48560011, 1.03032173, 1.89505988, 1.82169126, 1.88858915])